# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='languageCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_country', models.CharField(max_length=255)),
                ('language_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='popularPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('plan_name', models.CharField(max_length=255)),
                ('plan_id', models.IntegerField()),
                ('payment_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trendingMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('movie_id', models.IntegerField()),
            ],
        ),
    ]
